from django.urls import path
from chatting_service.controller import (
    get_conversations,
    edit_message_view,
    delete_message_view,
    toggle_reaction_view,
    forward_message_view,
    search_messages_view,
    pin_chat_view,
    unpin_chat_view,
    archive_chat_view,
    unarchive_chat_view,
    mute_chat_view,
    unmute_chat_view,
    block_user_view,
    unblock_user_view,
    report_user_view,
)

urlpatterns = [
    path("conversations/", get_conversations, name="get_conversations"),
    path("conversations/<int:target_user_id>/pin/", pin_chat_view, name="pin_chat"),
    path("conversations/<int:target_user_id>/unpin/", unpin_chat_view, name="unpin_chat"),
    path("conversations/<int:target_user_id>/archive/", archive_chat_view, name="archive_chat"),
    path("conversations/<int:target_user_id>/unarchive/", unarchive_chat_view, name="unarchive_chat"),
    path("conversations/<int:target_user_id>/mute/", mute_chat_view, name="mute_chat"),
    path("conversations/<int:target_user_id>/unmute/", unmute_chat_view, name="unmute_chat"),
    path("users/<int:target_user_id>/block/", block_user_view, name="block_user"),
    path("users/<int:target_user_id>/unblock/", unblock_user_view, name="unblock_user"),
    path("users/<int:target_user_id>/report/", report_user_view, name="report_user"),
    path("messages/search/", search_messages_view, name="search_messages"),
    path("messages/<int:message_id>/edit/", edit_message_view, name="edit_message"),
    path("messages/<int:message_id>/delete/", delete_message_view, name="delete_message"),
    path("messages/<int:message_id>/for-me/", delete_message_view, name="delete_message_for_me"),
    path("messages/<int:message_id>/reactions/", toggle_reaction_view, name="toggle_reaction"),
    path("messages/<int:message_id>/forward/", forward_message_view, name="forward_message"),
    path("messages/<int:message_id>/", edit_message_view, name="edit_message_alt"),
]
