# Generated by Django 6.1 on 2026-08-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_service', '0002_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_public_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
