# Generated by Django 6.1 on 2026-08-23 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], db_index=True, default='sent', max_length=10),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'status'], name='messages_receive_c6df42_idx'),
        ),
    ]
