# Generated by Django 6.1 on 2026-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting_service', '0002_message_status_message_messages_receive_c6df42_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
