# Generated by Django 6.1 on 2026-08-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting_service', '0006_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forwarded_from_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
