# Generated by Django 6.1 on 2026-08-29 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting_service', '0012_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='reported_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_reports', to='chatting_service.message'),
        ),
    ]
